Реализован базовый функционал Hacker News
JstUsername/hacker-news pull request #1
Opened 2024-07-22 17:43 UTC by JstUsername

https://stackblitz.com/edit/vitejs-vite-vjmdmv

2024-07-22 17:51 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.tsx
> +  const { newsItem, setExpandVisible } = useNewsItemState();
На лекции говорил, что так нельзя)

2024-07-22 17:52 UTC, IvanKoigerov commented on src/theme.ts
> +    background: '"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'400\' height=\'400\' viewBox=\'0 0 800 800\'%3E%3Cg fill=\'none\' stroke=\'%23022741\' stroke-width=\'1\'%3E%3
не такую тему лучше в тему не закидывать)

2024-07-25 19:16 UTC, Kimiyori commented
словил баг, время неверно отображается
![image](https://github.com/user-attachments/assets/a7f7ae9b-9b7e-42d2-9981-995708e388c8)

2024-07-25 19:20 UTC, Kimiyori requested changes

2024-07-25 19:20 UTC, Kimiyori commented on src/components/CommentsItem/CommentsItem.styled.ts
> +import ArrowIcon from '../../assets/pixel-arrow.svg?react';
лучше на абсолютные пути переписать наверное

2024-07-25 19:20 UTC, Kimiyori commented on src/components/Header/Header.tsx
> +      <HNLogo title="Logo" onClick={() => navigate('/')} />
почему не в <a> тага?

2024-07-25 19:20 UTC, Kimiyori commented on src/components/NewsList/NewsList.tsx
> +  }, [newsList, getNewsList]);
а в рекурсию не упадет?

2024-07-25 19:20 UTC, Kimiyori commented on src/components/NewsList/NewsList.tsx
> +          time_ago={newsItem.time_ago}
{...newsItem}

2024-07-25 19:20 UTC, Kimiyori commented on src/components/NewsList/NewsList.tsx
> +    return <InternalServerError />;
не хочешь потрогать suspense? от таких костылей избавились бы

2024-07-25 19:20 UTC, Kimiyori commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +    const minutes = date.getMinutes().toString().padStart(2, '0');
мб в функцию pad вынести?

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +      !auto ? set({ newsLoading: false }) : null;
&&

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +      get().newsList.every((oldNewsItem) => newNewsItem.id !== oldNewsItem.id),
я до конца не понял, а в чем смысл?) у этой штуки сложность O(n*m), но зачем?

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +    set({ newsList: newData.concat(get().newsList).slice(0, 100) });
а, у тебя же 100 итемов сплошным списком идут... Может лучше пагинацию добавить?

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +    const response = await fetch(`${newsListUrl[0]}?t=${new Date().getTime()}`);
почему обновляется только первая часть списка?

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +    };
имеет смысл вынести функцию наверно...и так громоздко выходит

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +    };
я честно вообще не понимаю зачем тут стор используется) всмысле это вполне все решается построением дерева и менеджменом состояний видимости комментов в самом компоненте)

2024-07-25 19:20 UTC, Kimiyori commented on src/store/store.ts
> +    };
казалось бы функция просто на получение итема новости, а столько внешнй работы)

2024-07-25 19:33 UTC, JstUsername commented on src/store/store.ts
> +    set({ newsList: newData.concat(get().newsList).slice(0, 100) });
Условие задание такое...
"Показывает последние 100 новостей в виде списка, отсортированного по дате, самые свежие сверху".
https://github.com/web-bee-ru/ru-test-assignments/blob/main/react/01-news-list.md

2024-07-25 19:38 UTC, JstUsername commented on src/store/store.ts
> +    const response = await fetch(`${newsListUrl[0]}?t=${new Date().getTime()}`);
Это сделано специально, чтобы каждый раз не кидать по 4 запроса.
Логика такая:
У нас в любом случае раз в минуту происходит автоматическое обновление последних новостей, причем при автоматическом обновлении идет сравнение id'шников и новые новости добавляются только если их не существует. Это еще пояснение к твоему комментарию чуть выше, где пишешь про сложность O(n*m).
И при ручном обновлении соответственно нам тоже достаточно сделать один запрос, и выделить те новости, которые появились с момента последнего автоматического обновления до момента когда мы вызвали ручное обновление.

2024-07-25 19:39 UTC, JstUsername commented on src/store/store.ts
> +      get().newsList.every((oldNewsItem) => newNewsItem.id !== oldNewsItem.id),
Чуть ниже описал смысл и почему используется при обновлении только один запрос.

2024-07-25 20:27 UTC, IvanKoigerov commented on src/components/Header/Header.tsx
> +      <HNLogo title="Logo" onClick={() => navigate('/')} />
Почему не тег А 
Правильно, нужно в таких местах использовать ашки потому что это линк
То есть на нее можно правой кнопкой мыши кликать и открывать в новой вкладке
Или средней и тд

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +import ArrowIcon from '../../assets/pixel-arrow.svg?react';
Не парься в стажерских тасках это не нужно

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +  }
Не круто что ты стили пишешь через теги, хоть и у тебя есть родитель, просто лучше такого избегать

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +`;
А почему не {$isVisible: boolean}? просто, чтобы отдельные сущности не плодить, как тип в данном случае

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.tsx
> +        </>
тебе тут не нужны `<></>`

`comment.comments.length ? comment.comments.map : null`
так код будет чище 
Почему тут null? потому что comment.comments.length может быть 0 и тогда он отобразиться на странице

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/Footer/Footer.styled.ts
> +  }
обычно межу тем как ты открываешь `{}` не важно где оставляют пустую строку перед и после, для лучшей читабельности

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/Footer/Footer.styled.ts
> +  right: 0;
Не вижу смысла указывать эти значения для футера, растяни его по другому. Просто нет смылса использовать у релетив в принципе эти параметры, просто может быть опасно, что-то где-то может отобразиться не корректно

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/Header/Header.styled.ts
> +  }
В текущих реалях, лучше всего такие блоки в принципе выпиливать из дома, а не описывать display: none;
Лишний компонент, который никогда не отрисуется на экране, но так как тут ты просто styled используешь то лан пох

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/Header/Header.styled.ts
> +`;
ну тут тоже самое что и с прошлым

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/Header/Header.styled.ts
> +export const ButtonLink = styled('button')`
ButtonLink кнопки не юзаем для линков

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/Header/Header.styled.ts
> +export const ButtonLink = styled('button')`
Кстати, не знаю у тебя карточни новостей a или нет, но желательно, чтобы тоже были линками карточки, это важно для конечного удобства пользователя

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/InternalServerError/InternalServerError.styled.ts
> +  }
Когда такие вещи пишешь, лучше всего описывай в комменте что это такое, что за 88 и 64
чьи это размеры, почему делаешь такой calc

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/InternalServerError/InternalServerError.styled.ts
> +  }
Ну и по возможности таких вещей лучше избегать, никто не знает, когда у тебя может неожиданно измениться размер той же шапки и тд

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/InternalServerError/InternalServerError.styled.ts
> +`;
лучше всего для таких вещей по семантике использовать span

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/InternalServerError/InternalServerError.styled.ts
> +`;
Лучше всего в одном месте определить h1 с типами ${({ theme }) => theme.typography.h1}; 
и потом уже его в styled закидывать 
Так будет реально проще

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/InternalServerError/InternalServerError.styled.ts
> +`;
В другом файле похожий компонент, лучше все равно их немного по разному называть 
Да и будто бы опять же тут стили повторяются какие-то
Можешь вынести их в какой-то общий абстрактный button

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/NewsList/NewsList.styled.ts
> +  }
второй раз вижу, вынечи эту вещь опять же в какой-то общий компонент, а тут реюзай

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/NewsList/NewsList.tsx
> +  }, [newsList, getNewsList]);
Лучше писать такие вещи не через && или ? : 
А через if, так будет понятнее всего, да и при маунте компонента, корректнее всего было бы перезапрашивать данные под копотом, особенно в ситуации, когда они у тебя так часто меняются

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/NewsList/NewsList.tsx
> +  );
Не круто таки жесткие if писать, лучше всегда такие вещи стараться избегать, тк, у тебя размаунтиться все новости, а потом заново будут маунтиться, из-за этого ты можешь просесть по производительности

2024-07-25 22:02 UTC, IvanKoigerov commented on src/components/NewsList/NewsList.tsx
> +  }
ну ошибку норм так выносить, но да Максим правильно говорит, стоит потрогать suspense

2024-07-25 22:02 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.styled.ts
> +  box-sizing: border-box;
такие вещи должны быть в css reset или нормалайз, на каждом проекте желательно их использовать

2024-07-25 22:02 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.styled.ts
> +`;
ну также теги не круто описывать

2024-07-25 22:02 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +  };
еба дроч, потрогай оч крутую библиотеку date fns

2024-07-25 22:02 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +  const getNewsContent = useSelectorGetNewsContent();
Помнишь какое было первое задание (тудушки)? лучше всего подумать как можно распределить компоненты, чтобы избежать таких лютых подписок на все

2024-07-25 22:02 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +}
Слишком много вещей делаешь для return, очень нечитабельно выглядит 
Ну и NotFound нужно уж тогда делать раньше 
так же как и лоудер 
Ну и лучше на ошибку сделать один общий компонент, который будет отвечать за отрисовку всех ошибок

2024-07-25 22:02 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +}
Также у тебя повторяется 3 вещи 
Ошибка, лоудер и children, звучит как то, что можно легко вынести в какой-то Layout

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +      const response = await fetch(`${newsListUrl[i]}?t=${new Date().getTime()}`);
странно, что не используешь Promise.all

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +      i === 3 ? (fetchPromise = fetchPromise.slice(0, 10)) : null;
Внутри кода не описывай никогда таким образом работу с проверкой данных, темы нечитабельная
Через if сильно понятнее

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +      get().newsList.every((oldNewsItem) => newNewsItem.id !== oldNewsItem.id),
по настощему будто бы дешевле было бы просто получать все и отрисовывать, педставь сколько у тебя по итогу происходит пробегов по целому массиву

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +    set({ newsList: newData.concat(get().newsList).slice(0, 100) });
Ну да, давай оставим эту сотню, тут все корректно
А пагинация норм тема, но сейчас это будет дольше делать

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +    !auto ? set({ newsLoading: false }) : null;
много раз повторяешь это слово, корректнее все было бы просто сделать это один раз в начале и один раз в конце

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +      const response = await fetch(`${newsListUrl[i]}?t=${new Date().getTime()}`);
он бы в разы упростил бы твой код и сделал бы его более понятным

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +}));
Я бы на твоем месте бы по избежании ререндеров, ладно уж, один раз пробежался бы по массиву, если нет новых id то сеть значение, если нет то не сеть, иначе это дороговато таким заниматься на каждый запрос

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +const useNewsItemState = create<UseNewsItemType>((set) => ({
Нужно бить на два файла, не круто держать два стора в одном файле

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +    let foundNews = newsList.find((news) => news.id === id);
много используешь let, где оно тебе не нужно, не помню какая там структура данных, но как я помню, тебе будто бы не нужна информация о том какой там news из newsList, просто по id получай значение через запрос

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +      switch (commentsList.level) {
это визуальная тема, не вижу смысла хранить эту информацию в сторе, согласен с Максимом

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +    let foundNews = newsList.find((news) => news.id === id);
Эта штука релеванта, только если ты кешишь, все открытые юзером страницы новостей, без этого просто используем запрос

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +  getNewsItem: async (id, newsList, auto) => {
очень усложнил эту тему, в этой функции тебе нужно только лишь получать информацию бэка о новости

2024-07-25 22:02 UTC, IvanKoigerov commented on src/store/store.ts
> +  },
соответственно лучше это не хранить в сторе

2024-07-25 22:02 UTC, IvanKoigerov commented on src/theme.ts
Лучше всего делить тему и GlobalStyle
Для разных вещей они и описывать их лучше в разных файлах

2024-07-26 04:23 UTC, Kimiyori commented on src/store/store.ts
> +    const response = await fetch(`${newsListUrl[0]}?t=${new Date().getTime()}`);
Окей, добавляются новые новости, а старые обновляться не будут? там же могут измениться тоже данные. Твой подход работал бы только в случае с пагинацией, и то надо бы номер страницы еще прокидывать

2024-07-26 04:26 UTC, Kimiyori commented on src/components/CommentsItem/CommentsItem.tsx
> +        </>
мне наоборот нравится через &&

2024-07-28 14:42 UTC, JstUsername commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +    const minutes = date.getMinutes().toString().padStart(2, '0');
Функция переписана с применением date-fns.

2024-08-03 18:06 UTC, JstUsername commented on src/components/CommentsItem/CommentsItem.styled.ts
> +  }
Здесь стилизуется контент, который получается из запроса, не совсем понимаю как по - другому стилизовать.
`<CommentsItemContent dangerouslySetInnerHTML={{ __html: comment.content }} />`

2024-08-05 15:58 UTC, Kimiyori requested changes

2024-08-05 15:58 UTC, Kimiyori commented on src/components/CommentsItem/CommentsItem.styled.ts
> +`;
убери вложенные стили

2024-08-05 15:58 UTC, Kimiyori commented on src/components/CommentsItem/CommentsItem.styled.ts
> +  display: ${({ $isVisible }) => ($isVisible ? 'block' : 'none')};
убери

2024-08-05 15:58 UTC, Kimiyori commented on src/components/CommentsItem/CommentsItem.tsx
> +      {comment.comments?.map((childComment: NewsItemType) => {
а это замени на это
 {isExpandVisible && comment.comments?.map((childComment: NewsItemType) => {
 мы же обговаривали это)

2024-08-05 15:58 UTC, Kimiyori commented on src/components/ErrorHandler/ErrorHandler.tsx
> +        <RefreshButton onClick={() => window.location.reload()}>reloadPage()</RefreshButton>
вообще хорошо бы через navigate делать роутинг, а фукнцию возвращения передавать через проп

2024-08-05 15:58 UTC, Kimiyori commented on src/components/NewsContentBlock/NewsContentBlock.tsx
> +    newsItem !== null && (
просто проверяй на булевое значение с помощью !!

2024-08-05 15:58 UTC, Kimiyori commented on src/components/ErrorHandler/ErrorHandler.tsx
> +        <RefreshButton onClick={() => window.location.reload()}>reloadPage()</RefreshButton>
потому что по сообщению выдавать рендер ну такое себе) хотя бы поставь этот текст в консту какую-нибудь чотбы в нескольких местах ее не править если что

2024-08-05 15:58 UTC, Kimiyori commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +    setIsPageNotFound((prev) => !prev && true);
зачем это тут?

2024-08-05 15:58 UTC, Kimiyori commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +    setIsPageNotFound((prev) => !prev && true);
что мешает бросать ошибку в самой функции запроса?

2024-08-05 15:58 UTC, Kimiyori commented on src/store/states/newsItemState/newsItemState.ts
> +    return null;
вообще странно что только 500 обрабатываешь, есть и другие коды)

2024-08-05 15:58 UTC, Kimiyori commented on src/components/NewsContentBlock/NewsContentBlock.tsx
> +    return lightFormat(date, 'HH:mm dd.MM.yy').toString();
функцию можно вынести в какую-нибудь utils

2024-08-05 15:58 UTC, Kimiyori commented on src/components/NewsContentBlock/NewsContentBlock.tsx
> +            <By>
что за <By>? давай нормально называть!

2024-08-05 15:58 UTC, Kimiyori commented on src/components/NewsItem/NewsItem.tsx
> +  }, [setIsPageNotFound, newsItem]);
та же история, зачем тут это?

2024-08-12 08:27 UTC, IvanKoigerov commented on src/App.tsx
> +              <Route path="*" element={<ErrorHandler error={new Error('Page not found')} clearLayout={true} />} />
`clearLayout` обычно пишем просто его

2024-08-12 08:27 UTC, IvanKoigerov commented on src/App.tsx
> +        <ErrorBoundary FallbackComponent={ErrorHandler}>
У него вроде свой каллбэк есть у Reасt Router

2024-08-12 08:27 UTC, IvanKoigerov commented on src/commons/Text/Text.ts
> +`;
Ты не можешь ждать что вариант это какой-то там стринг, по логике это должно быть четкие значение, которые ты можешь ввести, то есть четкий тип. А то новый человек на проекте будет страдать и не понимать какие же есть варианты, да и тебе будет проще

2024-08-12 08:27 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +`;
Не убрал

2024-08-12 08:27 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +export const ExpandIcon = styled(ArrowIcon)<{ $isVisibleIcon: boolean; $isExpand: boolean | undefined }>`
`$isExpand: boolean | undefined` почему именно такой? 
почему не $isExpand?: boolean
Тебе нужно чтобы разраб обязательно указал это значение?

2024-08-12 08:27 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.styled.ts
> +`;
transition мб добавить?

2024-08-12 08:27 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.tsx
> +  );
старайся избегать лишних вещей в своей html, тут нет особого смысла использовать ещё один див будто бы. ни в ретерне ни в теле

2024-08-12 08:27 UTC, IvanKoigerov commented on src/components/CommentsItem/CommentsItem.tsx
> +          return (
ыы пустой строчки тут нет

2024-08-12 08:27 UTC, IvanKoigerov commented on src/theme.ts
> +  },
такое себе название непонятно на месте что это за высота то, нужно исправлять и привязывать к сущности

2024-08-12 08:27 UTC, IvanKoigerov commented on src/utils/timestampToAgo.ts
обычно вся работа с датами лежит в одном файле, чтобы проще было работать, и в одном файле можно было найти все

2024-08-12 08:27 UTC, IvanKoigerov commented on src/styles/GlobalStyle.ts
> +    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='400' viewBox='0 0 800 800'%3E%3Cg fill='none' stroke='%23022741' stroke-width='1'%3E%3Cpath
вешаешь стили на body, я уже ругал тебя за это, этого делать нельзя, не на всех страницах ты можешь захотеть видеть это

2024-08-12 08:27 UTC, IvanKoigerov commented on src/pages/NewsItemPage/NewsItemPage.tsx
> +    setIsPageNotFound((prev) => !prev && true);
А шо ничего не сделал? @JstUsername

2024-08-14 07:33 UTC, merged